version: "3.5"

networks:
    cohbuilder:
        external: false

services:
    server:
        build: .
        image: cohbuilder_api
        container_name: cohbuilder_api
        networks:
            - cohbuilder
        volumes:
            - /var/coh-builder:/data
            - /var/www/coh-builder:/frontend
        ports:
            - "${HTTP_PORT}:80"
