services:
  coh_builder_frontend:
    image: nginx
    container_name: coh_builder_frontend
    volumes:
      - "./default.conf.template:/etc/nginx/templates/default.conf.template"
      - "./dist:/var/www/coh-builder:ro"
    ports:
      - ${WEB_PORT}:80
    environment:
      - API_PORT=8080
      - NGINX_ENVSUBST_FILTER=^(API_PORT)$$
